baseURL: "https://floriancaumont-cloud.github.io/pm_playbook/"
languageCode: "en-us"
title: "PM Playbook"
theme: "PaperMod"

pagination:
  pagerSize: 10

enableRobotsTXT: true

params:
  defaultTheme: auto
  ShowReadingTime: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
